### ISSUE TITLE
READ FARM text list

### ISSUE THREAD

**Issue by READFARM-FF** [PreAngel/pre-angel.com#14]
[PreAngel素材_Milestone.xlsx](https://github.com/PreAngel/pre-angel.com/files/3626128/PreAngel._Milestone.xlsx)

**Comment by huan** [comment]
I had removed the video file in the PR because:

1. its resolution is too low. we need at lease 740p, and the HD with 1080p would be better.
1. it should be uploaded to YouTube and QQ Video so that we could be able to embed it on our web page.

Can you upload the HD video to YouTube and QQ Video, and then post the URL here, then we will be able to embed it in our pages!

**Comment by READFARM-FF** [comment]
Alright. Let me get a reliable vpn first. :)

**Comment by huan** [comment]
@READFARM-FF Great. I'm looking for our videos online!

**Comment by READFARM-FF** [comment]
I have uploaded a demo video onto YouTube. Here's the URL, https://youtu.be/c5Pccuy65l0. Can you please check it whether available or not? Thx.

**Comment by huan** [comment]
Yes, it's available and looks great!

We need also to upload it to the qq video so that we can link it on our webpage and make it playable for the visitors from inside China.

**Comment by huan** [comment]
Please notice that the size of our company logo is too small.

https://pre-angel.com/assets/portfolios/readfarm/icon.png

Current it is 140x138, which should be at least 160x160, and a 500x500 png would be great.

**Comment by READFARM-FF** [comment]
Got it. I'll do it again at qq video ASAP.

**Comment by READFARM-FF** [comment]
I'm afraid I don't have a clearer vectorial logo. Let me find out how can I fix it.

**Comment by READFARM-FF** [comment]
QQ video URL, https://v.qq.com/x/page/n3005own2gj.html @huan

**Comment by huan** [comment]
Good job!

Please embed the video on our company page so that the visitors can play it.

**Comment by READFARM-FF** [comment]
Alright. 
Should I create a new file in 'assests' or just paste the URL in the readfarm.md?

**Comment by huan** [comment]
Please have a look at <https://raw.githubusercontent.com/PreAngel/pre-angel.com/master/docs/_portfolios/mocha.md>.

We need to do the exact same with mocha: embed the qq video into our profile page.

**Comment by READFARM-FF** [comment]
Done. Well noted with thanks. I hope it can be work.

**Comment by huan** [comment]
I believe we are done this issue.
