### ISSUE TITLE
The icon image file ratio need to be optimized as 1:1

### ISSUE THREAD

**Issue by huan** [PreAngel/pre-angel.com#15]
The content of the company and people are good.

However, there have issues on the images.

1. The logo of the company should be corpped for vest showed by a round icon.
1. The avatar of all the people should be a square icon photo.

Please fix the images by sending a new PR , thanks.

See: https://pre-angel.com/portfolios/readfarm/

**Comment by READFARM-FF** [comment]
Got it. I've noticed the issue of the logo. I intend to send a new PR with all of our posts I just created, but I don't know how can I connect to the new pre-angel repository.

**Comment by huan** [comment]
Yes, we updated the repo to the new one.

So please re-fork this new one before you make any new update.

**Comment by huan** [comment]
@READFARM-FF We should not close any issue without any progress or explanation.

**Comment by READFARM-FF** [comment]
Got it.

**Comment by huan** [comment]
This should be fixed after the PR had been merged.
