### ISSUE TITLE
Interview for 海良

### ISSUE THREAD

**Issue by huan** [PreAngel/pre-angel.com#174]
https://shimo.im/docs/cf15f7066ea94b84

**Comment by hailiang-wang** [comment]
Related wtih https://github.com/PreAngel/pre-angel.com/commit/8e09de3ef2d56d977542fd71b45b266e132b8e13

Post https://pre-angel.com/chatopera-opensource-for-enterprises/

**Comment by huan** [comment]
Oh, it's great that we have it already! :+1:
