### ISSUE TITLE
[chatopera] update co-founder profile

### ISSUE THREAD

**Issue by Samurais** [PreAngel/pre-angel.com#75]
* update profile

**Comment by huan** [comment]
![image](https://user-images.githubusercontent.com/1361891/66885495-0ae92680-f007-11e9-96fd-054dc7ebd92d.png)

感觉图像比例和位置还是不太对，可能还需要再优化一下。

**Comment by Samurais** [comment]
![image](https://user-images.githubusercontent.com/3538629/66885740-d32eae80-f007-11e9-9d6b-6f4886bdc16c.png)

这个看上去可以吗？

**Comment by huan** [comment]
This one is better.

Can you add some more padding on the top?

See: 

![image](https://user-images.githubusercontent.com/1361891/66885800-083b0100-f008-11e9-83f1-e1b694daf880.png)

It would be better if Yu can look like you and Kai.

**Comment by huan** [comment]
The updated profile avatar looks great now, thanks!
