### ISSUE TITLE
Steamory Team, Enterprise Introduction and Articles

### ISSUE THREAD

**Issue by leinue** [PreAngel/pre-angel.com#8]
This is a discussion with @huan two days before the Mid-Autumn Festival in 2019. It can be put on the website of Pre-angel about Steamory（蒸汽记忆）:

- [x] The story of Authing: Why did I develop Authing? - Authing 的故事：我为什么开发 Authing
- [x] Why is modular productivity software just the beginning? - 为什么模块化生产力软件仅仅是一个开始
- [x]  How to build an efficient distributed R&D team? - 如何打造一个高效的分布式研发团队

Continuous iteration of content and title.

**Comment by huan** [comment]
Thank you very much for added all those news articles to the pa directory, Cheers!

Please feel free to optimize your profile in the directory at any time as needed, and send PR to publish the news about your company in the future when we have any!
